// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBfu0sdbd7sTwkdoWwRGfUKx7CrgdP0XJA',
    appId: '1:446199727825:web:db5ce3bc91ccd0e2c0e7f0',
    messagingSenderId: '446199727825',
    projectId: 'roshan-dastak-client',
    authDomain: 'roshan-dastak-client.firebaseapp.com',
    storageBucket: 'roshan-dastak-client.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCaEA5QLr0bEosGVPUyH27FxfaFlfMyw-Q',
    appId: '1:446199727825:android:e3d19231fea435b8c0e7f0',
    messagingSenderId: '446199727825',
    projectId: 'roshan-dastak-client',
    storageBucket: 'roshan-dastak-client.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBkr79e9oRgjGfq9dNEOwp1k6YESmSVbEY',
    appId: '1:446199727825:ios:2d528e7f7f0f5541c0e7f0',
    messagingSenderId: '446199727825',
    projectId: 'roshan-dastak-client',
    storageBucket: 'roshan-dastak-client.appspot.com',
    iosBundleId: 'com.example.roshanDastakClient',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBkr79e9oRgjGfq9dNEOwp1k6YESmSVbEY',
    appId: '1:446199727825:ios:2d528e7f7f0f5541c0e7f0',
    messagingSenderId: '446199727825',
    projectId: 'roshan-dastak-client',
    storageBucket: 'roshan-dastak-client.appspot.com',
    iosBundleId: 'com.example.roshanDastakClient',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBfu0sdbd7sTwkdoWwRGfUKx7CrgdP0XJA',
    appId: '1:446199727825:web:74e20468cf91cc7bc0e7f0',
    messagingSenderId: '446199727825',
    projectId: 'roshan-dastak-client',
    authDomain: 'roshan-dastak-client.firebaseapp.com',
    storageBucket: 'roshan-dastak-client.appspot.com',
  );
}
